name: kernel_2
channels:
  - conda-forge
  - rapidsai
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - alsa-lib=1.2.15.3
  - anyio=4.12.1
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.1.0
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - babel=2.17.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - bokeh=3.8.2
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.23.0
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=7.0.0
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - cmake=4.2.3
  - colorcet=3.1.0
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.14
  - cucim=25.12.00
  - cuda-bindings=12.9.5
  - cuda-cccl_linux-64=12.5.39
  - cuda-core=0.3.2
  - cuda-crt-dev_linux-64=12.5.82
  - cuda-crt-tools=12.5.82
  - cuda-cudart=12.5.82
  - cuda-cudart-dev=12.5.82
  - cuda-cudart-dev_linux-64=12.5.82
  - cuda-cudart-static=12.5.82
  - cuda-cudart-static_linux-64=12.5.82
  - cuda-cudart_linux-64=12.5.82
  - cuda-nvcc-dev_linux-64=12.5.82
  - cuda-nvcc-impl=12.5.82
  - cuda-nvcc-tools=12.5.82
  - cuda-nvrtc=12.5.82
  - cuda-nvvm-dev_linux-64=12.5.82
  - cuda-nvvm-impl=12.5.82
  - cuda-nvvm-tools=12.5.82
  - cuda-pathfinder=1.3.3
  - cuda-profiler-api=12.5.39
  - cuda-python=12.9.5
  - cuda-version=12.5
  - cudf=25.12.00
  - cudf-polars=25.12.00
  - cudf_kafka=25.12.00
  - cugraph=25.12.02
  - cuml=25.12.00
  - cupy=13.6.0
  - cupy-core=13.6.0
  - custreamz=25.12.00
  - cuvs=25.12.00
  - cuxfilter=25.12.00
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask=2025.9.2
  - dask-core=2025.9.2
  - dask-cuda=25.12.00
  - dask-cudf=25.12.00
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.20
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.9.2
  - distributed-ucxx=0.47.00
  - dlpack=0.8
  - double-conversion=3.4.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - fastrlock=0.8.3
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - frozenlist=1.7.0
  - fsspec=2026.1.0
  - gcc_impl_linux-64=13.4.0
  - gcc_linux-64=13.4.0
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geos=3.14.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - graphite2=1.3.14
  - gxx_impl_linux-64=13.4.0
  - gxx_linux-64=13.4.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.3.2
  - holoviews=1.22.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - imagecodecs=2026.1.14
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json-c=0.18
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-lsp=2.3.0
  - jupyter-server-proxy=4.4.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jxrlib=1.1
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.5
  - libarchive=3.8.5
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcrc32c=1.1.2
  - libcublas=12.5.3.2
  - libcublas-dev=12.5.3.2
  - libcucim=25.12.00
  - libcudf=25.12.00
  - libcudf_kafka=25.12.00
  - libcufft=11.2.3.61
  - libcufile=1.10.1.7
  - libcufile-dev=1.10.1.7
  - libcugraph=25.12.02
  - libcugraph_etl=25.12.02
  - libcuml=25.12.00
  - libcumlprims=25.12.00
  - libcups=2.3.3
  - libcurand=10.3.6.82
  - libcurand-dev=10.3.6.82
  - libcurl=8.18.0
  - libcusolver=11.6.3.83
  - libcusolver-dev=11.6.3.83
  - libcusparse=12.5.1.3
  - libcusparse-dev=12.5.1.3
  - libcuvs=25.12.00
  - libcuvs-headers=25.12.00
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=13.4.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.12.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - libkvikio=25.12.00
  - liblapack=3.11.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnuma=2.0.18
  - libnvcomp=5.0.0.6
  - libnvcomp-dev=5.0.0.6
  - libnvimgcodec=0.6.0
  - libnvimgcodec0=0.6.0
  - libnvjitlink=12.9.86
  - libnvjpeg=12.3.2.81
  - libnvjpeg2k0=0.9.0.43
  - libnvtiff=0.5.1.75
  - libnvtiff0=0.5.1.75
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libprotobuf=6.31.1
  - libraft=25.12.00
  - libraft-headers=25.12.00
  - libraft-headers-only=25.12.00
  - librdkafka=2.8.0
  - libre2-11=2025.11.05
  - librmm=25.12.00
  - librttopo=1.1.0
  - libsanitizer=13.4.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=13.4.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libucxx=0.47.00
  - libudev1=258.3
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.1.2
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - linkify-it-py=2.0.3
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.4.5
  - lz4-c=1.10.0
  - lzo=2.10
  - make=4.4.1
  - mapclassify=2.10.0
  - markdown=3.10.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - minizip=4.0.10
  - mistune=3.2.0
  - msgpack-python=1.1.2
  - multidict=6.7.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - muparser=2.3.5
  - narwhals=2.16.0
  - nbclient=0.10.4
  - nbconvert-core=7.17.0
  - nbformat=5.10.4
  - nccl=2.29.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - nodejs=25.2.1
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numba-cuda=0.19.2
  - numpy=2.2.6
  - nvidia-ml-py=13.590.48
  - nvtx=0.2.14
  - nx-cugraph=25.12.00
  - openjpeg=2.5.4
  - openjph=0.26.0
  - openldap=2.6.10
  - openssl=3.6.1
  - orc=2.2.2
  - overrides=7.7.0
  - packaging=26.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - panel=1.8.7
  - param=2.3.1
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - phik=0.12.5
  - pillow=12.1.0
  - pip=26.0
  - pixman=0.46.4
  - platformdirs=4.5.1
  - polars=1.34.0
  - polars-runtime-32=1.34.0
  - proj=9.7.1
  - prometheus-cpp=1.3.0
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.2.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=3.1.2
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pyct=0.6.0
  - pygments=2.19.2
  - pylibcudf=25.12.00
  - pylibcugraph=25.12.02
  - pylibraft=25.12.00
  - pyogrio=0.12.1
  - pyparsing=3.3.2
  - pyproj=3.7.2
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.11.14
  - python-confluent-kafka=2.8.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.11.14
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pywavelets=1.9.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.10.1
  - raft-dask=25.12.00
  - rapids=25.12.00
  - rapids-dask-dependency=25.12.01
  - rapids-logger=0.2.3
  - rapids-xgboost=25.12.00
  - rav1e=0.7.1
  - rdma-core=61.0
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rhash=1.4.6
  - rich=14.3.2
  - rmm=25.12.00
  - rpds-py=0.30.0
  - s2n=1.6.2
  - scikit-image=0.24.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=2.1.0
  - setuptools=80.10.2
  - shapely=2.1.2
  - simpervisor=1.0.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8.3
  - sqlite=3.51.2
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - streamz=0.6.5
  - svt-av1=4.0.0
  - sysroot_linux-64=2.39
  - tblib=3.2.2
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2026.1.28
  - tinycss2=1.5.1
  - tk=8.6.13
  - tomli=2.4.0
  - toolz=1.1.0
  - tornado=6.5.4
  - tqdm=4.67.2
  - traitlets=5.14.3
  - treelite=4.6.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - uc-micro-py=1.0.3
  - ucx=1.19.1
  - ucxx=0.47.00
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.6.3
  - wayland=1.24.0
  - wcwidth=0.5.3
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.46.3
  - xarray=2026.1.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.3.0
  - xgboost=3.1.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - duckdb==1.4.4
      - lightgbm==4.6.0
      - mpmath==1.3.0
      - sympy==1.14.0
prefix: /home/ramon/miniconda3/envs/kernel_2
