name: kernel_4
channels:
  - conda-forge
  - rapidsai
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.2=h206d751_0
  - azure-identity-cpp=1.13.3=hed0cdb0_1
  - azure-storage-blobs-cpp=12.16.0=hdd73cc9_1
  - azure-storage-common-cpp=12.12.0=ha7a2c86_1
  - azure-storage-files-datalake-cpp=12.14.0=h52c5a47_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cachetools=7.0.1=pyhd8ed1ab_0
  - cairo=1.18.4=he90730b_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h724c32c_4
  - cuda-bindings=12.9.5=py311hff0572f_0
  - cuda-cccl_linux-64=12.5.39=ha770c72_0
  - cuda-core=0.5.1=cuda12_py311hc26999e_1
  - cuda-crt-dev_linux-64=12.5.82=ha770c72_0
  - cuda-crt-tools=12.5.82=ha770c72_0
  - cuda-cudart=12.5.82=he02047a_0
  - cuda-cudart-dev=12.5.82=he02047a_0
  - cuda-cudart-dev_linux-64=12.5.82=h85509e4_0
  - cuda-cudart-static=12.5.82=he02047a_0
  - cuda-cudart-static_linux-64=12.5.82=h85509e4_0
  - cuda-cudart_linux-64=12.5.82=h85509e4_0
  - cuda-nvcc-dev_linux-64=12.5.82=ha770c72_0
  - cuda-nvcc-impl=12.5.82=hd3aeb46_0
  - cuda-nvcc-tools=12.5.82=hd3aeb46_0
  - cuda-nvrtc=12.5.82=he02047a_0
  - cuda-nvvm-dev_linux-64=12.5.82=ha770c72_0
  - cuda-nvvm-impl=12.5.82=h59595ed_0
  - cuda-nvvm-tools=12.5.82=h59595ed_0
  - cuda-pathfinder=1.3.4=pyhcf101f3_0
  - cuda-profiler-api=12.5.39=ha770c72_0
  - cuda-python=12.9.5=pyh698daf1_0
  - cuda-version=12.5=hd4f0392_3
  - cudf=25.12.00=cuda12_py311_251210_580975be
  - cuml=25.12.00=cuda12_py311_251211_5c22c200
  - cupy=13.6.0=py311h72da3fd_2
  - cupy-core=13.6.0=py311he30c881_2
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.20=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dlpack=0.8=h59595ed_3
  - double-conversion=3.4.0=hecca717_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastrlock=0.8.3=py311hc665b79_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.3.2=h6083320_0
  - icu=78.2=h33c6efd_0
  - ipykernel=7.2.0=pyha191276_1
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - libabseil=20260107.1=cxx17_h7b12aa8_0
  - libarrow=21.0.0=h2603568_18_cpu
  - libarrow-acero=21.0.0=h635bf11_18_cpu
  - libarrow-compute=21.0.0=h53684a4_18_cpu
  - libarrow-dataset=21.0.0=h635bf11_18_cpu
  - libarrow-substrait=21.0.0=hb4dd7c2_18_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.5.3.2=he02047a_0
  - libcublas-dev=12.5.3.2=he02047a_0
  - libcudf=25.12.00=cuda12_251210_580975be
  - libcufft=11.2.3.61=he02047a_0
  - libcufile=1.10.1.7=he02047a_0
  - libcufile-dev=1.10.1.7=he02047a_0
  - libcuml=25.12.00=cuda12_251211_5c22c200
  - libcumlprims=25.12.00=cuda12_py310_251211_7e1ef293
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.6.82=he02047a_0
  - libcurand-dev=10.3.6.82=he02047a_0
  - libcurl=8.18.0=h4e3cde8_0
  - libcusolver=11.6.3.83=he02047a_0
  - libcusolver-dev=11.6.3.83=he02047a_0
  - libcusparse=12.5.1.3=he02047a_0
  - libcusparse-dev=12.5.1.3=he02047a_0
  - libcuvs=25.12.00=cuda12_251211_fc27938b
  - libcuvs-headers=25.12.00=cuda12_251211_fc27938b
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_17
  - libgoogle-cloud=2.39.0=h9d11ab5_1
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_1
  - libgrpc=1.78.0=h1d1128b_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkvikio=25.12.00=cuda12_251210_61297197
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnuma=2.0.18=hb9d3cd8_3
  - libnvcomp=5.0.0.6=hb7e823c_3
  - libnvcomp-dev=5.0.0.6=hb7e823c_3
  - libnvjitlink=12.9.86=hecca717_2
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=h9692893_2
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_2
  - libparquet=21.0.0=h7376487_18_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.55=h421ea60_0
  - libpq=18.2=hb80d175_0
  - libprotobuf=6.33.5=h2b00c02_0
  - libraft=25.12.00=cuda12_251211_d226bc96
  - libraft-headers=25.12.00=cuda12_251211_d226bc96
  - libraft-headers-only=25.12.00=cuda12_251211_d226bc96
  - libre2-11=2025.11.05=h0dc7533_1
  - librmm=25.12.00=cuda12_251210_86731e05
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libsystemd0=259.1=h6569c3e_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libucxx=0.47.00=cuda12_251210_5d6f0af3
  - libudev1=259.1=h6569c3e_0
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libvulkan-loader=1.4.341.0=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=3.1.2=rapidsai_hc3bde56_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py311h1741904_2
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib=3.10.8=py311h38be061_0
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nccl=2.29.3.1=h4d09622_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h54a6638_1
  - numba=0.61.2=py311h6220fa4_2
  - numba-cuda=0.19.2=pyhcf101f3_0
  - numpy=2.2.6=py311h5d046bc_0
  - nvidia-ml-py=13.590.48=pyhd8ed1ab_0
  - nvtx=0.2.14=py311h49ec1c0_1
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.2=hbb90d81_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py311hed34c8f_2
  - parso=0.8.6=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.1=py311hf88fc01_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py311haee01d2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.2=rapidsai_pyh395bae7_1
  - pyarrow=21.0.0=py311h38be061_3
  - pyarrow-core=21.0.0=py311h342b5a4_3_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylibcudf=25.12.00=cuda12_py311_251210_580975be
  - pylibraft=25.12.00=cuda12_py311_251211_d226bc96
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py311he4c1a5a_0
  - python=3.11.14=hd63d673_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.2=hb82b983_4
  - rapids-logger=0.2.3=h98325ef_0
  - rdma-core=61.0=h192683f_0
  - re2=2025.11.05=h5301d42_1
  - readline=8.3=h853b02a_0
  - rich=14.3.2=pyhcf101f3_0
  - rmm=25.12.00=cuda12_py311_251210_86731e05
  - s2n=1.6.2=he8a4886_1
  - scikit-learn=1.8.0=np2py311ha15b03d_1
  - scipy=1.16.3=py311hbe70eeb_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py311h0372a8f_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h366c992_103
  - tornado=6.5.4=py311h41d9c34_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - treelite=4.6.1=py311h72b0140_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucx=1.19.1=h63b5c0b_0
  - ucxx=0.47.00=cuda12_py311_251210_5d6f0af3
  - unicodedata2=17.0.1=py311h49ec1c0_0
  - wayland=1.24.0=hd6090a7_1
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - cloudpickle==3.1.2
      - duckdb==1.4.4
      - lightgbm==4.6.0
      - mpmath==1.3.0
      - shap==0.50.0
      - slicer==0.0.8
      - sympy==1.14.0
      - tqdm==4.67.3
prefix: /home/ramon/miniconda3/envs/kernel_4
