name: tcc_gpu
channels:
  - conda-forge
  - rapidsai
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.1=he9688bd_4
  - aws-c-cal=0.9.5=h346e085_1
  - aws-c-common=0.12.5=hb03c661_0
  - aws-c-compression=0.3.1=h7e655bb_7
  - aws-c-event-stream=0.5.6=h1deb5b9_4
  - aws-c-http=0.10.6=hd09dbd4_1
  - aws-c-io=0.23.2=h6b699b9_1
  - aws-c-mqtt=0.13.3=hdd0c675_7
  - aws-c-s3=0.8.6=h2c9161e_6
  - aws-c-sdkutils=0.2.4=h7e655bb_2
  - aws-checksums=0.2.7=h7e655bb_3
  - aws-crt-cpp=0.35.0=h542abf0_1
  - aws-sdk-cpp=1.11.606=h522d481_5
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py311h7c6b74e_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - cffi=2.0.0=py311h03d9500_1
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311hdf67eae_2
  - cuda-bindings=13.0.3=py311h1ddb823_1
  - cuda-cccl_linux-64=13.0.85=ha770c72_0
  - cuda-core=0.3.2=py311h2cd87c0_0
  - cuda-crt-dev_linux-64=13.0.88=ha770c72_0
  - cuda-crt-tools=13.0.88=ha770c72_0
  - cuda-cudart=13.0.96=hecca717_0
  - cuda-cudart-dev=13.0.96=hecca717_0
  - cuda-cudart-dev_linux-64=13.0.96=h376f20c_0
  - cuda-cudart-static=13.0.96=hecca717_0
  - cuda-cudart-static_linux-64=13.0.96=h376f20c_0
  - cuda-cudart_linux-64=13.0.96=h376f20c_0
  - cuda-nvcc-dev_linux-64=13.0.88=he91c749_0
  - cuda-nvcc-impl=13.0.88=h85509e4_0
  - cuda-nvcc-tools=13.0.88=he02047a_0
  - cuda-nvrtc=13.0.88=hecca717_0
  - cuda-nvvm-dev_linux-64=13.0.88=ha770c72_0
  - cuda-nvvm-impl=13.0.88=h4bc722e_0
  - cuda-nvvm-tools=13.0.88=h4bc722e_0
  - cuda-pathfinder=1.3.2=pyhcf101f3_0
  - cuda-profiler-api=13.0.85=h7938cbb_0
  - cuda-python=13.0.3=pyhd8ed1ab_1
  - cuda-version=13.0=hc7b4dd1_3
  - cudf=25.10.00=cuda13_py311_251008_f4e35ca0
  - cuml=25.10.00=cuda13_py311_251008_f9fcdbb0
  - cupy=13.6.0=py311h3416b12_2
  - cupy-core=13.6.0=py311h2124c9d_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cytoolz=1.1.0=py311h49ec1c0_1
  - dask=2025.9.1=pyhcf101f3_0
  - dask-core=2025.9.1=pyhcf101f3_0
  - dask-cuda=25.10.00=py313_251008_472ca1ce
  - dask-cudf=25.10.00=cuda13_py311_251008_f4e35ca0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2025.9.1=pyhcf101f3_0
  - distributed-ucxx=0.46.00=py_251008_64355220_h9c9281c
  - dlpack=0.8=h59595ed_3
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastrlock=0.8.3=py311hc665b79_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=21.0.0=h552f9d5_11_cuda
  - libarrow-acero=21.0.0=hb826db4_11_cuda
  - libarrow-compute=21.0.0=h58682fd_11_cuda
  - libarrow-dataset=21.0.0=hb826db4_11_cuda
  - libarrow-substrait=21.0.0=h9d9f3f8_11_cuda
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang-cpp21.1=21.1.4=default_h99862b1_0
  - libclang13=21.1.4=default_h746c552_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=13.1.0.3=h676940d_0
  - libcublas-dev=13.1.0.3=h676940d_0
  - libcudf=25.10.00=cuda13_251008_f4e35ca0
  - libcufft=12.0.0.61=hecca717_0
  - libcufile=1.15.1.6=hbc026e6_0
  - libcufile-dev=1.15.1.6=hecca717_0
  - libcuml=25.10.00=cuda13_251008_f9fcdbb0
  - libcumlprims=25.10.00=cuda13_py310_251008_7b289cfd
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.4.0.35=h676940d_1
  - libcurand-dev=10.4.0.35=h676940d_1
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=12.0.4.66=h676940d_1
  - libcusolver-dev=12.0.4.66=h676940d_1
  - libcusparse=12.6.3.3=hecca717_0
  - libcusparse-dev=12.6.3.3=hecca717_0
  - libcuvs=25.10.00=cuda13_251008_f245c152
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkvikio=25.10.00=cuda13_0_251008_fb6220c4
  - liblapack=3.9.0=38_h47877c9_openblas
  - libllvm21=21.1.4=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnuma=2.0.18=hb9d3cd8_3
  - libnvcomp=5.0.0.6=h7bcfba5_3
  - libnvcomp-dev=5.0.0.6=h7bcfba5_3
  - libnvjitlink=13.0.88=hecca717_0
  - libnvptxcompiler-dev=13.0.88=ha770c72_0
  - libnvptxcompiler-dev_linux-64=13.0.88=ha770c72_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h31208bf_11_cuda
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - libraft=25.10.00=cuda13_251008_521611f8
  - libraft-headers=25.10.00=cuda13_251008_521611f8
  - libraft-headers-only=25.10.00=cuda13_251008_521611f8
  - libre2-11=2025.08.12=h7b12aa8_1
  - librmm=25.10.00=cuda13_251008_7aaad1de
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.9=h996ca69_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libucxx=0.46.00=cuda13_251008_64355220
  - libudev1=257.9=h085a93f_0
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=3.0.5=rapidsai_h432d1f4_3
  - libxkbcommon=1.12.3=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py311h1741904_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py311h63cca24_1
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib=3.10.7=py311h38be061_0
  - matplotlib-base=3.10.7=py311h0f3be63_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311hdf67eae_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.10.1=pyhcf101f3_0
  - nccl=2.28.7.1=hd557bf5_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h54a6638_1
  - numba=0.61.2=py311h6220fa4_2
  - numba-cuda=0.19.1=pyhcf101f3_2
  - numpy=2.2.6=py311h5d046bc_0
  - nvidia-ml-py=13.580.82=pyhd8ed1ab_0
  - nvtx=0.2.13=py311h49ec1c0_1
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hed34c8f_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py311h07c5bb8_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311haee01d2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.5=rapidsai_pyh4bd9c9a_3
  - pyarrow=21.0.0=py311h38be061_1
  - pyarrow-core=21.0.0=py311hbce1db7_1_cuda
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylibcudf=25.10.00=cuda13_py311_251008_f4e35ca0
  - pylibraft=25.10.00=cuda13_py311_251008_521611f8
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py311he4c1a5a_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hd63d673_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - raft-dask=25.10.00=cuda13_py311_251008_521611f8
  - rapids-dask-dependency=25.10.00=251008_bcfdc48e
  - rapids-logger=0.1.1=h98325ef_0
  - rdma-core=60.0=hecca717_0
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - rich=14.2.0=pyhcf101f3_0
  - rmm=25.10.00=cuda13_py311_251008_7aaad1de
  - s2n=1.5.27=h30d3c1c_1
  - scikit-learn=1.7.2=py311hc3e1efb_0
  - scipy=1.16.3=py311h1e13796_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py311h49ec1c0_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - treelite=4.4.1=py311hd96400b_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucx=1.19.0=h567e125_5
  - ucxx=0.46.00=cuda13_py311_251008_64355220
  - unicodedata2=16.0.0=py311h49ec1c0_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xgboost=3.0.5=rapidsai_pyh13f938f_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py311haee01d2_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/rcramos/miniconda3/envs/tcc_gpu
